### ISSUE TITLE
Investigate why latest version of Docker was not installed by Ansible

### ISSUE THREAD

**Issue by amit-kumar-4** [SapInnovation/swarm-using-ansible#10]
Latest available version: v18
Installed version :v17

**Comment by neerajagr** [comment]
As the swarm was deployed using Ansible and the role was used from Ansible galaxy (atosatto.docker-swarm), This particular role was installing the docker-engine not the docker-ce. The docker-engine present state is 17.03 and this is why the docker version was showing as 17.03 . The custom role needs to be created with the use of docker-ce which will install the docker version 18.03.
